#!/bin/sh
set -e

if [ "$1" = "remove" ]; then
    lighty-disable-mod radio >/dev/null 2>&1 || true
    rm -f /etc/php/*/fpm/pool.d/zz-radio.conf
    systemctl restart lighttpd >/dev/null 2>&1 || true
    systemctl restart 'php*-fpm.service' >/dev/null 2>&1 || true
fi
